version: "3"
services:
  backend:
    container_name: gasession-spring
    image: ${SPRING_BOOT_IMAGE}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - default_bridge

  mysql:
    container_name: gasession-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    networks:
      default_bridge:
        ipv4_address: 172.16.3.4

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24