name: 'CD'  # Workflow name
on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setting gradle.properties
        run: |
          echo "${{ secrets.GRADLE_PROPERTIES }}" >> gradle.properties
          cat gradle.properties

      - name: Docker image build
        run: ./gradlew bootBuildImage

      - name: Connect EC2
        run: |
          echo "$SSH_PEM_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_KNOWN_HOSTS} '~/script.sh'
        env:
          SSH_USER: ${{secrets.AWS_USERNAME}}
          SSH_KNOWN_HOSTS: ${{secrets.AWS_HOST}}
          SSH_PEM_KEY: ${{secrets.AWS_SSH_KEY_PEM}}

      - name: check
        run: ls