name: 'CD'  # Workflow name
on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setting gradle.properties
        run: |
          echo "${{ secrets.GRADLE_PROPERTIES }}" >> gradle.properties
          cat gradle.properties

      - name: Docker image build
        run: ./gradlew bootBuildImage

#      - name: Connect EC2
#        run: |
#          echo "$SSH_PEM_KEY" >> $HOME/key.pem
#          chmod 400 $HOME/key.pem
#          ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ${SSH_USER}@${SSH_HOST} "echo 'Connected to EC2'"
#        env:
#          SSH_USER: ${{secrets.AWS_USER}}
#          SSH_KNOWN_HOSTS: ${{secrets.AWS_HOST}}
#          SSH_PEM_KEY: ${{secrets.AWS_SSH_KEY_PEM}}

      - uses: appleboy/ssh-action@master
        with:
          host: 서버명[~~ap-northeast-2.compute.amazonaws.com로 시작하는 서버명을 적음]
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull [계정명]/spring-cicd:${GITHUB_SHA::7}
            docker tag [계정명]/spring-cicd:${GITHUB_SHA::7} spring-cicd
            docker stop server
            docker run -d --rm --name server -p 80:8080 spring-cicd

